// app/layout.tsx
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Script from "next/script"; // <-- Import Script from next/script

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/*
          New: Define onRecaptchaLoad globally and synchronously in the HTML
          This ensures the function is present before the reCAPTCHA script loads.
        */}
        <script
          dangerouslySetInnerHTML={{
            __html: `
              window.onRecaptchaLoad = function() {
                console.log("SUCCESS: reCAPTCHA v2 script loaded directly!");
                // You can perform other actions here if needed once reCAPTCHA is ready
                // For example: if (typeof grecaptcha !== 'undefined') console.log('grecaptcha object:', grecaptcha);
              };
            `,
          }}
        />

        {/*
          New: reCAPTCHA v2 Script for Diagnostic Test
          This loads the standard reCAPTCHA v2 API.
          'onload=onRecaptchaLoad' in the src URL means the script will call window.onRecaptchaLoad
          when it's ready.
        */}
        <Script
          src="https://www.google.com/recaptcha/api.js?onload=onRecaptchaLoad&render=explicit"
          strategy="beforeInteractive" // Use beforeInteractive to ensure it's loaded as early as possible
          async
          defer
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
