name: Deploy to Firebase App Hosting

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm install

      # Diagnostic: Check if TEST_SECRET_VALUE is properly retrieved
      # This step should still work and confirm secret retrieval.
      - name: Debug Test Secret
        run: echo "The TEST_SECRET_VALUE is: ${{ secrets.TEST_SECRET_VALUE }}"

      # Build Next.js Application with FIREBASE_ADMIN_SDK_CONFIG
      # CRITICAL FIX: Base64 decode FIREBASE_ADMIN_SDK_CONFIG_BASE64 secret
      # and export as FIREBASE_ADMIN_SDK_CONFIG for the build process.
      - name: Build Next.js Application
        env:
          # This secret holds the Base64 encoded raw JSON string for FIREBASE_ADMIN_SDK_CONFIG
          FIREBASE_ADMIN_SDK_CONFIG_BASE64: ${{ secrets.FIREBASE_ADMIN_SDK_CONFIG_BASE64 }}
        run: |
          # Decode the Base64 secret into a temporary variable
          DECODED_FIREBASE_ADMIN_SDK_CONFIG=$(echo "$FIREBASE_ADMIN_SDK_CONFIG_BASE64" | base64 -d)
          # Export it as an environment variable for npm run build
          export FIREBASE_ADMIN_SDK_CONFIG="$DECODED_FIREBASE_ADMIN_SDK_CONFIG"
          npm run build

      # Install Firebase CLI
      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      # Authenticate Firebase CLI with Service Account
      # We use the Base64 encoded FIREBASE_SERVICE_ACCOUNT_PROJECT_X_68603 secret for this, then decode it.
      - name: Authenticate Firebase CLI with Service Account
        env:
          # This secret holds the Base64 encoded JSON content for the service account key
          GOOGLE_SERVICE_ACCOUNT_JSON_BASE64: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_PROJECT_X_68603 }}
        run: |
          # Decode the Base64 secret and write it to a temporary file
          echo "$GOOGLE_SERVICE_ACCOUNT_JSON_BASE64" | base64 -d > /tmp/service-account-key.json
          # Set the GOOGLE_APPLICATION_CREDENTIALS environment variable for subsequent steps
          echo "GOOGLE_APPLICATION_CREDENTIALS=/tmp/service-account-key.json" >> $GITHUB_ENV
      # Deploy to Firebase App Hosting using CLI
      - name: Deploy to Firebase App Hosting using CLI
        run: firebase apphosting:deploy --project project-x-68603 --backend-id linguaverse-web --input-directory out
