name: Deploy to Firebase App Hosting

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm install
      - run: npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v1.2.0 # CRITICAL CHANGE: Explicitly set to v1.2.0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_PROJECT_X_68603 }}'
          projectId: 'project-x-68603'
          backendId: 'linguaverse-web'
          rootDirectory: '/'
          publicDirectory: 'out'
          # buildEnvironment: This block is currently removed to get the YAML to parse.
          # We will re-add it once the action itself is found and executed.
          #   FIREBASE_ADMIN_SDK_CONFIG: '${{ secrets.FIREBASE_ADMIN_SDK_CONFIG }}'
