name: Deploy to Firebase App Hosting

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm install

      - name: Debug Test Secret
        run: echo "The TEST_SECRET_VALUE is: ${{ secrets.TEST_SECRET_VALUE }}"

      - name: Build Next.js Application
        env:
          FIREBASE_ADMIN_SDK_CONFIG_BASE64: ${{ secrets.FIREBASE_ADMIN_SDK_CONFIG_BASE64 }}
        run: |
          DECODED_FIREBASE_ADMIN_SDK_CONFIG=$(echo "$FIREBASE_ADMIN_SDK_CONFIG_BASE64" | base64 -d)
          export FIREBASE_ADMIN_SDK_CONFIG="$DECODED_FIREBASE_ADMIN_SDK_CONFIG"
          npm run build

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Authenticate Firebase CLI with Service Account
        env:
          GOOGLE_SERVICE_ACCOUNT_JSON_BASE64: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_PROJECT_X_68603 }}
        run: |
          echo "$GOOGLE_SERVICE_ACCOUNT_JSON_BASE64" | base64 -d > /tmp/service-account-key.json
          echo "GOOGLE_APPLICATION_CREDENTIALS=/tmp/service-account-key.json" >> $GITHUB_ENV

      - name: Deploy to Firebase App Hosting using CLI
        run: firebase apphosting:deploy --project project-x-68603 --backend-id linguaverse-web --input-directory out
