name: Deploy to Firebase App Hosting

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm install

      # Diagnostic: Check if TEST_SECRET_VALUE is properly retrieved
      - name: Debug Test Secret
        run: echo "The TEST_SECRET_VALUE is: ${{ secrets.TEST_SECRET_VALUE }}"

      # Build Next.js Application with FIREBASE_ADMIN_SDK_CONFIG
      - name: Build Next.js Application
        run: npm run build
        env:
          FIREBASE_ADMIN_SDK_CONFIG: '${{ secrets.FIREBASE_ADMIN_SDK_CONFIG }}'

      # Install Firebase CLI
      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      # Authenticate Firebase CLI with Service Account
      - name: Authenticate Firebase CLI with Service Account
        env:
          GOOGLE_SERVICE_ACCOUNT_JSON: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_PROJECT_X_68603 }}
        run: |
          echo "$GOOGLE_SERVICE_ACCOUNT_JSON" > /tmp/service-account-key.json
          echo "GOOGLE_APPLICATION_CREDENTIALS=/tmp/service-account-key.json" >> $GITHUB_ENV

      # Deploy to Firebase App Hosting using CLI
      - name: Deploy to Firebase App Hosting using CLI
        run: firebase apphosting:deploy --project project-x-68603 --backend-id linguaverse-web --input-directory out
